### ISSUE TITLE
Question: why so many proto imports?

### ISSUE THREAD

**Issue by meling** [alta/protopatch#12]
This looks great @ydnar ... thanks for doing this.

I’m wondering why use several different options for this; can’t this be done with a single option `go.options` for all the things, and figure out at “patch” time which type of patch it should be?

Alternatively, if this isn’t possible or desirable, I think it would be nicer to have a single import for all options.

**Comment by ydnar** [comment]
Unfortunately you can’t have two extensions with the same name in a single proto package namespace. Even if they extend different things.

I tried different syntax, eg `go.message_options` but felt that the additional imports were an acceptable trade-off for the consistent dot notation.

It does alias go.field.options to go.options because they’re most commonly used.

**Comment by meling** [comment]
Thanks. I checked the code after creating the issue, and remembered what you just said. But wouldn’t it be better to keep all options in a single proto to avoid many imports?

**Comment by meling** [comment]
Hmm. So maybe you can’t have those options defined in a single proto because of the naming... (didn’t read your first response carefully enough.) I’ll think more/check before asking again.

**Comment by ydnar** [comment]
> Hmm. So maybe you can’t have those options defined in a single proto because of the naming... (didn’t read your first response carefully enough.) I’ll think more/check before asking again.

Yeah, that’s the issue. If it were possible, I agree that using `go.options` for all extensions would be preferable. If we consolidated into a single import, the API would look something like this:

- `go.enum_options`
- `go.value_options`
- `go.message_options`
- `go.field_options`
- `go.oneof_options`

Thinking about this further, I suppose we could do this and drop the `_options` suffix, so the API would be:

- `(go.enum) = {name: 'Foo', …}`
- `(go.value) = {…}`
- `(go.message) = {…}`
- `(go.field) = {…}`
- `(go.oneof) = {…}`

**Comment by meling** [comment]
Yeah, I like that API :-)
