### ISSUE TITLE
use of external plugins breaks generated code

### ISSUE THREAD

**Issue by Adphi** [alta/protopatch#21]
We often use other plugins like `protoc-gen-validate` or `protoc-gen-grpc-gateway`, but tools renaming fields usually breaks the generated code. The chosen approach by `protopatch` may solve this issue but does not work right now.
I did implement a [naive cache](https://github.com/Adphi/protopatch/tree/cache) that store `protoc-gen-go` output and reload it before patching generated code by other plugins, allowing the ast tree to find the type's declarations. I can create a pull request if you wish.
Another approach would have been to re-run `protoc-gen-go` plugin before each (other) plugin call to retrieve the types declaration.
I don't know which would be best.
Any thought ?

**Comment by ydnar** [comment]
Yeah, I struggled with this issue. Unfortunately the `protobuf-go` authors refused to implement hooks to allow a plugin to modify generated names prior to serialization.

I suppose an alternative method for implementing this would be to post-process generated Go code as a final step. This would exist outside of a `protoc` plugin, but would have the benefit of being able to modify any generated code, not just protobuf code.

**Comment by Adphi** [comment]
The solution I implemented follows this simple principle:
- As soon as we want to patch the generated go code, we need to patch every plugin

Here is an example :

*pb/interfaces.proto* :
```protobuf
syntax = "proto3";

package interfaces;

option go_package = "pb;interfaces";

import "patch/go.proto";
import "protoc-gen-validate/validate/validate.proto";

message Interface {
  string name = 1;
  enum Status {
    UNKNOWN = 0 [(go.value).name = "StatusUnknown"];
    UP = 1 [(go.value).name = "StatusUP"];
    DOWN = 2 [(go.value).name = "StatusDown"];
  }
  Status status = 2 [(validate.rules).enum = {defined_only: true, not_in: [0]}];
  repeated IpAddress addresses = 3;
}

message IpAddress {
  option (go.message).name = "IPAddress";
  oneof Address {
    string ip_v4 = 3 [(go.field).name = "IPV4", (validate.rules).string.ipv4 = true];
    string ip_v6 = 4 [(go.field).name = "IPV6", (validate.rules).string.ipv6 = true];
  }
}
```

*Makefile*:
```Makefile
.PHONY:
proto:
	@protoc -I. -Ithird_party --go-patch_out=plugin=go,paths=source_relative:. \
		--go-patch_out=plugin=validate,paths=source_relative,lang=go:. \
		pb/interfaces.proto
```

As we wrap both the generated go definitions and the `protoc-gen-validate` validate methods, both generated code are correctly patched.

You may find the changes I did [here](https://github.com/Adphi/protopatch/commit/83db7c363cf54dafb58e8abc8cfc71633bfef7b3)

**Comment by ydnar** [comment]
I’m confused. If you patch both plugins, why do you need the cache?

**Comment by ydnar** [comment]
Could you name your message `IPAddress` in the proto, rather than rename the Go message?

**Comment by Adphi** [comment]
The IpAddress is just for example purpose.
The first test I did (without cache) did generate incorect go code as only the interfaces.pb.go has correctly renamed fields / messages / enums.

**Comment by Adphi** [comment]
The plugin could not find the type declaration contained in the interfaces.pb.go as the wrap plugin generated code only contained the interfaces.pb.validate.go

**Comment by ydnar** [comment]
@Adphi would you mind sharing a minimal example repo or gist that shows how this works (or doesn’t work)? I feel like this is an important issue to resolve.

**Comment by Adphi** [comment]
@ydnar I did a small repo: https://github.com/Adphi/protopatch-uncache-test
can you please confirm the results ?

**Comment by ydnar** [comment]
@Adphi testing now.

BTW, we use `go list` to get the directory of the Google and protopatch protos when compiling, see `protopatch_module_path` below:

```Makefile
prunes = \( -path '*/.build/*' -o -path ./vendor -o -path '*/Pods/*' -o -path '*/gen/*' -o -path '*node_modules/*' \) -prune -o
go_proto_files = $(shell find .. $(prunes) -name '*.pb.go' -print)

protobuf_module = google.golang.org/protobuf
protobuf_module_path = $(shell go list -m -f {{.Dir}} $(protobuf_module))

protopatch_module = github.com/alta/protopatch
protopatch_module_path = $(shell go list -m -f {{.Dir}} $(protopatch_module))

go_out_path = ../internal

proto_files = $(sort $(shell find . -name '*.proto'))

.DEFAULT: generate
.PHONY: generate clean $(new_proto_files) $(proto_files)
generate: $(new_proto_files) $(proto_files)

$(proto_files):
	protoc \
		-I . \
		-I $(protobuf_module_path) \
		-I $(protopatch_module_path) \
		--go-patch_out=plugin=go,paths=source_relative:$(go_out_path) \
		--go-patch_out=plugin=go-grpc,paths=source_relative:$(go_out_path) \
		$@

clean:
	rm $(go_proto_files) $(swift_proto_files)
```

**Comment by ydnar** [comment]
OK. I’m wondering if your other suggestion of re-running the `go` plugin might be the best approach. Here’s what I’m thinking:

Instead of caching the `go` plugin output, and depending on a specific ordering for subsequent plugins, what if `protopatch` just assumes `plugin=go`, always runs it, and ensures its output is present for other plugins?

**Comment by Adphi** [comment]
I agree but don't like the computation overhead in case of the use of many plug-ins.
What may be an alternative will be to run it the first time if the plugin is not protoc-gen-go then use the cache for next processing.

**Comment by Adphi** [comment]
... but I don't know how to distinguish the first call between all.

**Comment by ydnar** [comment]
I see your point about CPU consumption when using multiple plugins. Given
that the source proto files for both `go` and `validate` are the same, I
wonder if we could ensure the symbols are correctly represented even when
the `go` plugin isn’t run.

**Comment by Adphi** [comment]
Maybe some hashing could help here?
