### ISSUE TITLE
Suggestion: Add 'prefix' to enum options

### ISSUE THREAD

**Issue by tandr** [alta/protopatch#9]
Errors in Go are usually prefixed with `Err`, and adding a custom name for each enum value is cumbersome and error prone 

It seems something like "prefix" feature would make life a bit easier

Compare

```Protobuf
enum Errors {
	option (go.enum.options) = {name: 'ProtocolErrors'};
	INVALID = 1 [(go.value.options) = {name: 'ErrInvalid'}];
	NOT_FOUND = 2 [(go.value.options) = {name: 'ErrNotFound'}];
	TOO_FUN = 3 [(go.value.options) = {name: 'ErrTooFun'}];
}
```

and

```Protobuf
enum Errors {
	option (go.enum.options) = {name: 'ProtocolErrors', prefix: 'Err'};
	INVALID = 1;
	NOT_FOUND = 2;
	TOO_FUN = 3;
}
```

should produce same results.

(I think (might be mistaken though) that contraction rules will replace `NOT_FOUND` and `TOO_FUN` with `NotFound` and `TooFun` correspondingly.)

Thank you very much!

(Found through https://github.com/gogo/protobuf/issues/691#issuecomment-646895641)

**Comment by ydnar** [comment]
Interesting. That would work similar to GoGo’s enum prefixing / naming extensions.

Currently, the generated Go enum value names can have stuttering type name + existing PREFIX_ (if specified to avoid clobbering values in generated C++).

I think this should be solved together.

**Comment by ydnar** [comment]
Hi there, now that stuttering prefixed names can be fixed with the `lint` option, and Go names for enum values can be specified directly, I’m going to close this. I don’t think it’s a good idea to have another API that duplicates already available functionality, even if it is verbose. A little duplication in Go is OK!
